[package]
name = "dbl_codebase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3.2"
rppal = {verion = "0.13.1", hal = true}
tcs3472 = "0.2.0"
